### ISSUE TITLE
The test file for Hello World is overly confusing and can turn off newcomers

### ISSUE THREAD

**Issue by trosel** [exercism/xperl6#297]
Compare Python's Hello World test file https://github.com/exercism/python/blob/master/exercises/hello-world/hello_world_test.py

To Perl 6's https://github.com/exercism/perl6/blob/master/exercises/hello-world/hello-world.t

Is there anyway to simplify Perl 6's testing files? Ideally, a test file that a student downloads would teach them how to set up a test. This file is sort of unreadable. 

`is hello, |.<expected description> for @($c-data<cases>);`

In order to test in Perl 6, first you must learn the entire language? Kind of defeats the purpose of Perl allowing for "baby talk" as well as Shakespeare.

**Comment by mienaikage** [comment]
PR open @ https://github.com/exercism/perl6/pull/298

**Comment by WildYorkies** [comment]
What if we shortened the entire thing to:

```perl6
#!/usr/bin/env perl6
use v6;
use Test;
use HelloWorld;
plan 1; # This is how many tests we expect to run.

is hello, "Hello, World!";
```

**Comment by mienaikage** [comment]
The absence of `use lib` is not ideal as it would require the user to set PERL6LIB themselves.

There is an existing PR to remove versioning @ https://github.com/exercism/perl6/pull/228, the reason it was there originally is because if a test file were changed, and someone attempted to run it against an older solution, comments would be made regarding failing tests. When a test is run the version check alerts the user not to expect all tests to succeed due to potential changes. It likely isn't needed anymore but need to make sure that it isn't.
